### ISSUE TITLE
Syntax error due to pyplot function "deprecated"

### ISSUE THREAD

**Issue by andre2007** [koji-kojiro/matplotlib-d#10]
File pyplot_functions.txt contains an entry ```deprecated``` which is also a D keyword

- dedent
- delaxes
- deprecated
- disconnect
- draw
- draw_all

This name causes the error
pyplot.d-mixin-41(191,6): Error: no identifier for declarator void
pyplot.d-mixin-41(191,18): Error: found ... when expecting )
pyplot.d-mixin-41(191,21): Error: declaration expected, not )
pyplot.d-mixin-41(191,63): Error: declaration expected, not if
pyplot.d-mixin-41(191,89): Error: no identifier for declarator a
pyplot.d-mixin-41(191,89): Error: declaration expected, not )

deprecated is a python decorator and therefore callable. Other decorators:
```dedent, silent_list, warn_deprecated```

**Comment by andre2007** [comment]
iscallable can be changed like this

```python
    def iscallable(name):
        ignore_decorators = ['dedent','deprecated','silent_list', 'warn_deprecated']
        return eval('callable(mod.{})'.format(name), scope) and name not in ignore_decorators
```

**Comment by andre2007** [comment]
@koji-kojiro Could you have a look?

**Comment by andre2007** [comment]
https://github.com/koji-kojiro/matplotlib-d/pull/11

**Comment by koji-kojiro** [comment]
merged. Thank you for your contribution!
