### ISSUE TITLE
Please create new release

### ISSUE THREAD

**Issue by andre2007** [koji-kojiro/matplotlib-d#12]
Could you create a new release? dub users facing the issue already solved with pr https://github.com/koji-kojiro/matplotlib-d/pull/11

https://forum.dlang.org/post/nnrbvjscwssqtxshcvjk@forum.dlang.org

**Comment by koji-kojiro** [comment]
Thanks for the report.
Now i'm out of the office, so I'll create a new release later.

**Comment by koji-kojiro** [comment]
I just published a new release. 
Thanks!
